### ISSUE TITLE
[Feature Request] use other translation services

### ISSUE THREAD

**Issue by pcause** [luhaifeng666/obsidian-translator#24]
Can you add options/use of other services like Google or Bing translate?

**Comment by luhaifeng666** [comment]
> Can you add options/use of other services like Google or Bing translate?

Of course~That's what I was thinking~

**Comment by inroading** [comment]
可以支持百度翻译API，以及deepL吗，谢谢

**Comment by luhaifeng666** [comment]
> 可以支持百度翻译API，以及deepL吗，谢谢

目前在做 bing 翻译的支持了，百度跟 deepL 的我会陆续支持~

**Comment by luhaifeng666** [comment]
This plugin has now supported two translation services: the [Youdao translation service](https://ai.youdao.com/#/) and the [Microsoft translation service](https://docs.microsoft.com/zh-cn/azure/cognitive-services/translator/quickstart-translator?tabs=csharp). You can enable them by setting `Enable` configuration.
<p align="center">

<img src="https://user-images.githubusercontent.com/9375823/185175027-c024cb36-332e-4524-8454-7e823f642c8f.png" />

</p>

**Comment by pcause** [comment]
great and thanks.  will close this

**Comment by luhaifeng666** [comment]
> great and thanks. will close this

Okay. I will add other translation services like Google, Baidu, etc. Stay tuned~
