### ISSUE TITLE
Please advise on the problem of not being able to copy

### ISSUE THREAD

**Issue by inroading** [luhaifeng666/obsidian-translator#26]
The dictionary definition text can't be selected, so it can't be copied, can this be improved? tkx

**Comment by luhaifeng666** [comment]
> The dictionary definition text can't be selected, so it can't be copied, can this be improved? tkx

Got it! Thanks for your feedback~

**Comment by luhaifeng666** [comment]
This problem has been solved. The version number is 0.1.3. 🫡
