### ISSUE TITLE
设置界面Enable按钮不可点击

### ISSUE THREAD

**Issue by Wanxp** [luhaifeng666/obsidian-translator#36]
系统版本:ubuntu22.04
Obsidian版本:v0.15.9
插件版本:xxx
操作: 下载安装插件, 点击设置
如图所示
![Screenshot from 2022-09-01 20-32-48](https://user-images.githubusercontent.com/26840810/187914517-ec3740d1-6d7b-4441-8679-0434bcc18d78.png)

**Comment by luhaifeng666** [comment]
目前插件兼容的平台是 MacOS，ubuntu 平台尚未做测试，因此会存在不兼容的情况。我会尽快兼容 ubuntu 平台~ 感谢支持与反馈~

**Comment by kettly1260** [comment]
windows平台也有同样的问题，无法选择

**Comment by luhaifeng666** [comment]
> windows平台也有同样的问题，无法选择

收到~

**Comment by luhaifeng666** [comment]
@Wanxp @kettly1260 问题已修复，请更新到0.3.1版本，看看是否还有问题~

**Comment by Wanxp** [comment]
windows已经可以了,感谢
