### ISSUE TITLE
插件加载不出来

### ISSUE THREAD

**Issue by yoghurtdewdew** [luhaifeng666/obsidian-translator#47]
![image](https://user-images.githubusercontent.com/63794438/218241703-68bba8c2-5153-42b1-9fbb-f0250067d627.png)
插件加载不出来 好奇怪

**Comment by luhaifeng666** [comment]
诶？奇怪。。。
麻烦提供下你的 Obsidian 版本以及系统信息呢? 我这边尝试下能不能复现~
感谢反馈~

**Comment by yoghurtdewdew** [comment]
我成功了！我又重新装了一下好了，估计是网络不稳定上次下载的文件有损坏，感谢！！

**Comment by luhaifeng666** [comment]
> 我成功了！我又重新装了一下好了，估计是网络不稳定上次下载的文件有损坏，感谢！！

好嘞~
